/* ═══════════════════════════════════════════════════════
   OmicsLab — Snakemake / Nextflow Pipeline Generator (Part 6)
   Generates boilerplate WGS / RNA-seq / GWAS pipelines
   for Snakemake (DSL2) and Nextflow (DSL2).
   ═══════════════════════════════════════════════════════ */
window.OmicsLab = window.OmicsLab || {};

OmicsLab.PipelineGen = (function () {

  const PIPELINES = {
    wgs_gatk: {
      label: 'WGS Variant Calling (GATK4)',
      desc: 'Whole-genome sequencing variant calling: FastQC → Trim Galore → BWA-MEM → GATK HaplotypeCaller → VQSR → annotation.',
      steps: ['FastQC (QC)','Trim Galore (trimming)','BWA-MEM2 (alignment)','SAMtools sort/markdup','GATK HaplotypeCaller (gVCF)','GATK GenotypeGVCFs','VQSR (variant filtering)','ANNOVAR / VEP (annotation)'],
      tools: ['FastQC','Trim Galore','BWA-MEM2','SAMtools','GATK4','ANNOVAR'],
      ref: 'GRCh38',
      smk: (cfg) => `# ══════════════════════════════════════════════
# OmicsLab WGS GATK4 Pipeline (Snakemake DSL2)
# Generated by OmicsLab Pipeline Generator
# ══════════════════════════════════════════════
configfile: "config.yaml"

SAMPLES = config["samples"]
REF = config["ref"]  # e.g. hg38.fa
DBSNP = config["dbsnp"]  # e.g. dbsnp_146.hg38.vcf.gz

rule all:
    input:
        expand("results/vcf/{sample}.filtered.vcf.gz", sample=SAMPLES),
        expand("results/qc/{sample}_fastqc.html", sample=SAMPLES)

rule fastqc:
    input: r1="data/{sample}_R1.fastq.gz", r2="data/{sample}_R2.fastq.gz"
    output: "results/qc/{sample}_fastqc.html"
    threads: 4
    shell: "fastqc {input.r1} {input.r2} -o results/qc/ -t {threads}"

rule trim:
    input: r1="data/{sample}_R1.fastq.gz", r2="data/{sample}_R2.fastq.gz"
    output:
        r1="results/trimmed/{sample}_R1_val_1.fq.gz",
        r2="results/trimmed/{sample}_R2_val_2.fq.gz"
    threads: 4
    shell: "trim_galore --paired --cores {threads} -o results/trimmed/ {input.r1} {input.r2}"

rule bwa_mem:
    input: r1="results/trimmed/{sample}_R1_val_1.fq.gz", r2="results/trimmed/{sample}_R2_val_2.fq.gz"
    output: "results/bam/{sample}.sorted.bam"
    threads: ${cfg.threads}
    params: rg="@RG\\\\tID:{sample}\\\\tSM:{sample}\\\\tPL:ILLUMINA"
    shell:
        "bwa-mem2 mem -t {threads} -R '{params.rg}' {REF} {input.r1} {input.r2} | "
        "samtools sort -@ {threads} -o {output}"

rule markdup:
    input: "results/bam/{sample}.sorted.bam"
    output:
        bam="results/bam/{sample}.markdup.bam",
        metrics="results/bam/{sample}.markdup.metrics"
    shell:
        "gatk MarkDuplicates -I {input} -O {output.bam} -M {output.metrics} && "
        "samtools index {output.bam}"

rule haplotypecaller:
    input: bam="results/bam/{sample}.markdup.bam"
    output: "results/gvcf/{sample}.g.vcf.gz"
    threads: ${cfg.threads}
    shell:
        "gatk HaplotypeCaller -R {REF} -I {input.bam} -O {output} "
        "-ERC GVCF --dbsnp {DBSNP} --native-pair-hmm-threads {threads}"

rule genotype_gvcfs:
    input: expand("results/gvcf/{sample}.g.vcf.gz", sample=SAMPLES)
    output: "results/vcf/cohort.raw.vcf.gz"
    shell:
        "gatk CombineGVCFs -R {REF} $(echo '{input}' | sed 's/ / -V /g' | sed 's/^/-V /') -O combined.g.vcf.gz && "
        "gatk GenotypeGVCFs -R {REF} -V combined.g.vcf.gz -O {output}"

rule vqsr:
    input: "results/vcf/cohort.raw.vcf.gz"
    output: "results/vcf/{sample}.filtered.vcf.gz"
    shell:
        "gatk VariantFiltration -V {input} "
        "--filter-expression 'QD < 2.0' --filter-name 'QD2' "
        "--filter-expression 'FS > 60.0' --filter-name 'FS60' "
        "-O {output}"
`,
      nxf: (cfg) => `// ══════════════════════════════════════════════
// OmicsLab WGS GATK4 Pipeline (Nextflow DSL2)
// Generated by OmicsLab Pipeline Generator
// ══════════════════════════════════════════════
nextflow.enable.dsl = 2

params {
    input   = "samplesheet.csv"
    ref     = "${cfg.ref || 'hg38.fa'}"
    dbsnp   = "dbsnp_146.hg38.vcf.gz"
    outdir  = "results"
    threads = ${cfg.threads}
}

process FASTQC {
    tag "\$sample_id"
    publishDir "\${params.outdir}/qc", mode: 'copy'
    input: tuple val(sample_id), path(r1), path(r2)
    output: path("*.html")
    script: "fastqc \$r1 \$r2 -t ${cfg.threads}"
}

process TRIM {
    tag "\$sample_id"
    input: tuple val(sample_id), path(r1), path(r2)
    output: tuple val(sample_id), path("*_val_1.fq.gz"), path("*_val_2.fq.gz")
    script: "trim_galore --paired --cores ${cfg.threads} \$r1 \$r2"
}

process BWA_MEM {
    tag "\$sample_id"
    input: tuple val(sample_id), path(r1), path(r2)
    output: tuple val(sample_id), path("\${sample_id}.sorted.bam")
    script:
    """
    bwa-mem2 mem -t ${cfg.threads} \\
        -R "@RG\\\\tID:\${sample_id}\\\\tSM:\${sample_id}\\\\tPL:ILLUMINA" \\
        \${params.ref} \$r1 \$r2 | samtools sort -@ ${cfg.threads} -o \${sample_id}.sorted.bam
    """
}

process MARKDUP {
    tag "\$sample_id"
    input: tuple val(sample_id), path(bam)
    output: tuple val(sample_id), path("\${sample_id}.markdup.bam")
    script: "gatk MarkDuplicates -I \$bam -O \${sample_id}.markdup.bam -M \${sample_id}.metrics && samtools index \${sample_id}.markdup.bam"
}

process HAPLOTYPECALLER {
    tag "\$sample_id"
    input: tuple val(sample_id), path(bam)
    output: tuple val(sample_id), path("\${sample_id}.g.vcf.gz")
    script: "gatk HaplotypeCaller -R \${params.ref} -I \$bam -O \${sample_id}.g.vcf.gz -ERC GVCF --dbsnp \${params.dbsnp} --native-pair-hmm-threads ${cfg.threads}"
}

workflow {
    ch_reads = Channel.fromPath(params.input)
        .splitCsv(header:true)
        .map { row -> tuple(row.sample, file(row.fastq_1), file(row.fastq_2)) }
    FASTQC(ch_reads)
    TRIM(ch_reads)
    BWA_MEM(TRIM.out)
    MARKDUP(BWA_MEM.out)
    HAPLOTYPECALLER(MARKDUP.out)
}
`,
    },
    rnaseq: {
      label: 'RNA-seq Differential Expression',
      desc: 'Bulk RNA-seq: FastQC → Trim → STAR → featureCounts → DESeq2 (R).',
      steps: ['FastQC','Trim Galore','STAR alignment','SAMtools sort','featureCounts','DESeq2 (R)'],
      tools: ['FastQC','Trim Galore','STAR','SAMtools','subread/featureCounts','DESeq2'],
      ref: 'GRCh38',
      smk: (cfg) => `# ══════════════════════════════════════════════
# OmicsLab RNA-seq Pipeline (Snakemake DSL2)
# ══════════════════════════════════════════════
configfile: "config.yaml"
SAMPLES = config["samples"]
STAR_INDEX = config["star_index"]
GTF = config["gtf"]

rule all:
    input:
        "results/counts/all_counts.txt",
        expand("results/qc/{sample}_fastqc.html", sample=SAMPLES)

rule fastqc:
    input: r1="data/{sample}_R1.fastq.gz", r2="data/{sample}_R2.fastq.gz"
    output: "results/qc/{sample}_fastqc.html"
    shell: "fastqc {input} -o results/qc/ -t 4"

rule trim:
    input: r1="data/{sample}_R1.fastq.gz", r2="data/{sample}_R2.fastq.gz"
    output: r1="results/trimmed/{sample}_R1.fq.gz", r2="results/trimmed/{sample}_R2.fq.gz"
    shell: "trim_galore --paired -o results/trimmed/ {input.r1} {input.r2}"

rule star_align:
    input: r1="results/trimmed/{sample}_R1.fq.gz", r2="results/trimmed/{sample}_R2.fq.gz"
    output: bam="results/bam/{sample}.Aligned.sortedByCoord.out.bam"
    threads: ${cfg.threads}
    shell:
        "STAR --runThreadN {threads} --genomeDir {STAR_INDEX} "
        "--readFilesIn {input.r1} {input.r2} --readFilesCommand zcat "
        "--outSAMtype BAM SortedByCoordinate "
        "--outFileNamePrefix results/bam/{wildcards.sample}. "
        "--outSAMattributes NH HI AS NM && samtools index {output.bam}"

rule feature_counts:
    input: expand("results/bam/{sample}.Aligned.sortedByCoord.out.bam", sample=SAMPLES)
    output: "results/counts/all_counts.txt"
    threads: ${cfg.threads}
    shell:
        "featureCounts -T {threads} -p -s 0 -a {GTF} -o {output} {input}"
`,
      nxf: (cfg) => `// ══════════════════════════════════════════════
// OmicsLab RNA-seq Pipeline (Nextflow DSL2)
// ══════════════════════════════════════════════
nextflow.enable.dsl = 2
params { input="samplesheet.csv"; star_index="star_index/"; gtf="genes.gtf"; outdir="results"; threads=${cfg.threads} }

process FASTQC {
    input: tuple val(id), path(r1), path(r2)
    output: path("*.html")
    script: "fastqc \$r1 \$r2 -t ${cfg.threads}"
}

process STAR {
    tag "\$id"
    input: tuple val(id), path(r1), path(r2)
    output: tuple val(id), path("\${id}.Aligned.sortedByCoord.out.bam")
    script:
    """
    STAR --runThreadN ${cfg.threads} --genomeDir \${params.star_index} \\
         --readFilesIn \$r1 \$r2 --readFilesCommand zcat \\
         --outSAMtype BAM SortedByCoordinate \\
         --outFileNamePrefix \${id}. --outSAMattributes NH HI AS NM
    """
}

process FEATURECOUNTS {
    input: path(bams)
    output: path("all_counts.txt")
    script: "featureCounts -T ${cfg.threads} -p -s 0 -a \${params.gtf} -o all_counts.txt \${bams}"
}

workflow {
    ch = Channel.fromPath(params.input).splitCsv(header:true).map { r -> tuple(r.sample, file(r.fastq_1), file(r.fastq_2)) }
    FASTQC(ch)
    STAR(ch)
    FEATURECOUNTS(STAR.out.map{it[1]}.collect())
}
`,
    },
    gwas: {
      label: 'GWAS QC + Association (Africa)',
      desc: 'African GWAS: sample QC → SNP QC → PCA → population stratification → SAIGE/PLINK2 association.',
      steps: ['Sample QC (PLINK2)','SNP QC (PLINK2)','LD pruning','PCA (PLINK2/FLASHPCA)','Ancestry check','SAIGE GWAS','Clumping + LocusZoom'],
      tools: ['PLINK2','FlashPCA','SAIGE','R','ANNOVAR'],
      ref: 'GRCh38',
      smk: (cfg) => `# ══════════════════════════════════════════════
# OmicsLab Africa GWAS Pipeline (Snakemake DSL2)
# ══════════════════════════════════════════════
configfile: "config.yaml"
INPUT_PLINK = config["plink_prefix"]  # BED/BIM/FAM without extension
PHENO = config["phenotype_file"]
COVAR = config["covariates_file"]
TRAIT = config["trait"]

rule all:
    input: "results/gwas/{TRAIT}.assoc.txt", "results/pca/pca.eigenvec"

rule sample_qc:
    input: multiext(INPUT_PLINK, ".bed",".bim",".fam")
    output: multiext("results/qc/step1_sampleqc", ".bed",".bim",".fam")
    shell:
        "plink2 --bfile {INPUT_PLINK} "
        "--mind 0.05 --geno 0.02 --hwe 1e-6 "
        "--maf ${cfg.maf || '0.01'} "
        "--out results/qc/step1_sampleqc"

rule ld_prune:
    input: multiext("results/qc/step1_sampleqc", ".bed",".bim",".fam")
    output: "results/pca/pruned.prune.in"
    shell:
        "plink2 --bfile results/qc/step1_sampleqc "
        "--indep-pairwise 50 10 0.1 --out results/pca/pruned"

rule pca:
    input: pruned="results/pca/pruned.prune.in", plink=multiext("results/qc/step1_sampleqc",".bed",".bim",".fam")
    output: "results/pca/pca.eigenvec"
    shell:
        "plink2 --bfile results/qc/step1_sampleqc "
        "--extract {input.pruned} --pca 20 --out results/pca/pca"

rule gwas_saige:
    input: plink=multiext("results/qc/step1_sampleqc",".bed",".bim",".fam"), pca="results/pca/pca.eigenvec"
    output: "results/gwas/{TRAIT}.assoc.txt"
    shell:
        "Rscript run_SAIGE_step1.R --phenoFile={PHENO} --covarColList=PC1,PC2,PC3,PC4,PC5,sex,age "
        "--phenoCol={TRAIT} --plinkFile=results/qc/step1_sampleqc --outputPrefix=results/gwas/{TRAIT}_step1 && "
        "Rscript run_SAIGE_step2.R --bgenFile=results/qc/step1_sampleqc --GMMATmodelFile=results/gwas/{TRAIT}_step1.rda "
        "--sampleFile=results/qc/step1_sampleqc.fam --SAIGEOutputFile={output}"
`,
      nxf: (cfg) => `// ══════════════════════════════════════════════
// OmicsLab Africa GWAS Pipeline (Nextflow DSL2)
// ══════════════════════════════════════════════
nextflow.enable.dsl = 2
params { plink="data/cohort"; pheno="pheno.txt"; trait="T2D"; outdir="results"; maf="${cfg.maf || '0.01'}" }

process SAMPLE_QC {
    input: path(plink_files)
    output: path("step1_sampleqc.{bed,bim,fam}")
    script: "plink2 --bfile \${params.plink} --mind 0.05 --geno 0.02 --hwe 1e-6 --maf \${params.maf} --out step1_sampleqc"
}

process PCA {
    input: path(plink_files)
    output: path("pca.eigenvec")
    script:
    """
    plink2 --bfile step1_sampleqc --indep-pairwise 50 10 0.1 --out pruned
    plink2 --bfile step1_sampleqc --extract pruned.prune.in --pca 20 --out pca
    """
}

process GWAS_SAIGE {
    input: path(plink_files); path(pca)
    output: path("\${params.trait}.assoc.txt")
    script:
    """
    Rscript run_SAIGE_step1.R --phenoFile=\${params.pheno} \\
        --covarColList=PC1,PC2,PC3,PC4,PC5,sex,age \\
        --phenoCol=\${params.trait} --plinkFile=step1_sampleqc \\
        --outputPrefix=\${params.trait}_step1
    Rscript run_SAIGE_step2.R --bgenFile=step1_sampleqc \\
        --GMMATmodelFile=\${params.trait}_step1.rda \\
        --SAIGEOutputFile=\${params.trait}.assoc.txt
    """
}

workflow {
    plink_ch = Channel.fromPath("\${params.plink}.{bed,bim,fam}").collect()
    SAMPLE_QC(plink_ch)
    pca_ch = PCA(SAMPLE_QC.out)
    GWAS_SAIGE(SAMPLE_QC.out, pca_ch)
}
`,
    },
  };

  let _activePipe = 'wgs_gatk';
  let _activeFw = 'smk';

  /* ── NLP pipeline suggestion (Prompt 46) ── */
  const NLP_MAP = [
    { patterns: /wgs|whole.genome|gatk|variant.call|snp.*indel/i,   pipe: 'wgs_gatk' },
    { patterns: /rna.?seq|expression|deseq|edger|transcript/i,       pipe: 'rnaseq' },
    { patterns: /gwas|population|admixture|plink|ancestry|struct/i,  pipe: 'gwas_africa' },
  ];

  function _nlpSuggest() {
    const q = (document.getElementById('pg-nlp-input')?.value || '').trim();
    if (!q) return;
    for (const { patterns, pipe } of NLP_MAP) {
      if (patterns.test(q)) { _selectPipe(pipe); OmicsLab.Toast?.show('Suggested: ' + PIPELINES[pipe].label, 'info'); return; }
    }
    OmicsLab.Toast?.show('Could not auto-detect — please select a pipeline manually', 'info');
  }

  /* ── SLURM batch script wrapper ── */
  function _wrapSlurm(code, cfg) {
    return `#!/bin/bash
#SBATCH --job-name=omicslab_pipeline
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=${cfg.threads}
#SBATCH --mem=64G
#SBATCH --time=24:00:00
#SBATCH --output=logs/pipeline_%j.out
#SBATCH --error=logs/pipeline_%j.err

# OmicsLab Pipeline — SLURM wrapper
# Generated by OmicsLab Pipeline Generator 2.0

mkdir -p logs results

# Run pipeline (Snakemake inside SLURM)
module load Snakemake/7.32.4 || true
snakemake --snakefile Snakefile --cores ${cfg.threads} --use-conda --rerun-incomplete "$@"

# ─── Snakemake pipeline follows ───
${code}`;
  }

  function _generate() {
    const pipe = PIPELINES[_activePipe];
    if (!pipe) return;
    const cfg = {
      threads: document.getElementById('pg-threads')?.value || '8',
      ref: document.getElementById('pg-ref')?.value || 'hg38.fa',
      maf: document.getElementById('pg-maf')?.value || '0.01',
    };
    let code = _activeFw === 'smk' ? pipe.smk(cfg) : _activeFw === 'slurm' ? _wrapSlurm(pipe.smk(cfg), cfg) : pipe.nxf(cfg);
    document.getElementById('pg-output').textContent = code;
    document.getElementById('pg-output-wrap').style.display = '';
  }

  function _copy() {
    const code = document.getElementById('pg-output')?.textContent || '';
    navigator.clipboard.writeText(code).catch(() => {});
    const btn = document.getElementById('pg-copy-btn');
    if (btn) { btn.textContent = 'Copied!'; setTimeout(() => btn.textContent = 'Copy', 1500); }
  }

  function _download() {
    const code = document.getElementById('pg-output')?.textContent || '';
    const ext = _activeFw === 'smk' ? 'Snakefile' : _activeFw === 'slurm' ? 'run_pipeline.sh' : 'main.nf';
    const blob = new Blob([code], { type:'text/plain' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = ext; a.click();
  }

  function _selectPipe(id) {
    _activePipe = id;
    document.querySelectorAll('.pg-pipe-btn').forEach(b => b.classList.toggle('pg-pipe-active', b.dataset.pid === id));
    const p = PIPELINES[id];
    document.getElementById('pg-pipe-desc').textContent = p?.desc || '';
    document.getElementById('pg-steps').innerHTML = (p?.steps || []).map(s => `<div class="pg-step">${s}</div>`).join('<div class="pg-step-arrow">→</div>');
    document.getElementById('pg-output-wrap').style.display = 'none';
  }

  function _selectFw(fw) {
    _activeFw = fw;
    document.querySelectorAll('.pg-fw-btn').forEach(b => b.classList.toggle('pg-fw-active', b.dataset.fw === fw));
    document.getElementById('pg-output-wrap').style.display = 'none';
  }

  function init() {
    const section = document.getElementById('pipeline-gen-section');
    if (!section || section.dataset.pgReady) return;
    section.dataset.pgReady = '1';
    const p0 = PIPELINES[_activePipe];
    section.innerHTML = `
      <div class="pg-wrap">
        <div class="pg-header">
          <div class="pg-header-title">
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#bc8cff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/></svg>
            Pipeline Generator 2.0
          </div>
          <div class="pg-header-sub">Generate Snakemake, Nextflow DSL2, or SLURM batch pipelines for common omics workflows</div>
        </div>
        <!-- NLP input (Prompt 46) -->
        <div class="pg-nlp-row">
          <input class="pg-nlp-input" id="pg-nlp-input" type="text" placeholder="Describe your analysis (e.g. &quot;WGS variant calling on malaria samples&quot;) and press Suggest…" autocomplete="off">
          <button class="pg-nlp-btn" onclick="OmicsLab.PipelineGen._nlpSuggest()">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
            Suggest
          </button>
        </div>
        <div class="pg-layout">
          <div class="pg-left">
            <div class="pg-section-label">Workflow</div>
            <div class="pg-pipe-list">
              ${Object.entries(PIPELINES).map(([id, p]) => `<button class="pg-pipe-btn${id===_activePipe?' pg-pipe-active':''}" data-pid="${id}" onclick="OmicsLab.PipelineGen._selectPipe('${id}')">${p.label}</button>`).join('')}
            </div>
            <div class="pg-section-label" style="margin-top:1rem">Framework</div>
            <div class="pg-fw-row">
              <button class="pg-fw-btn pg-fw-active" data-fw="smk" onclick="OmicsLab.PipelineGen._selectFw('smk')">Snakemake</button>
              <button class="pg-fw-btn" data-fw="nxf" onclick="OmicsLab.PipelineGen._selectFw('nxf')">Nextflow</button>
              <button class="pg-fw-btn" data-fw="slurm" onclick="OmicsLab.PipelineGen._selectFw('slurm')">SLURM</button>
            </div>
            <div class="pg-section-label" style="margin-top:1rem">Parameters</div>
            <div class="pg-params">
              <div class="pg-param-row">
                <label class="pg-param-label">Threads per rule</label>
                <input class="pg-param-input" id="pg-threads" type="number" value="8" min="1" max="128">
              </div>
              <div class="pg-param-row">
                <label class="pg-param-label">Reference FASTA path</label>
                <input class="pg-param-input" id="pg-ref" value="hg38.fa" placeholder="e.g. /data/ref/hg38.fa">
              </div>
              <div class="pg-param-row">
                <label class="pg-param-label">Min allele freq (GWAS)</label>
                <input class="pg-param-input" id="pg-maf" value="0.01" placeholder="0.01">
              </div>
            </div>
            <button class="pg-gen-btn" onclick="OmicsLab.PipelineGen._generate()">
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/></svg>
              Generate Pipeline
            </button>
          </div>
          <div class="pg-right">
            <div class="pg-pipe-desc" id="pg-pipe-desc">${p0.desc}</div>
            <div class="pg-steps" id="pg-steps">${p0.steps.map(s => `<div class="pg-step">${s}</div>`).join('<div class="pg-step-arrow">→</div>')}</div>
            <div class="pg-output-wrap" id="pg-output-wrap" style="display:none">
              <div class="pg-output-hdr">
                <span class="pg-output-label">Generated Pipeline</span>
                <div style="display:flex;gap:.4rem">
                  <button class="pg-act-btn" id="pg-copy-btn" onclick="OmicsLab.PipelineGen._copy()">Copy</button>
                  <button class="pg-act-btn" onclick="OmicsLab.PipelineGen._download()">Download</button>
                </div>
              </div>
              <pre class="pg-output" id="pg-output"></pre>
            </div>
          </div>
        </div>
      </div>`;
  }

  return { init, _generate, _copy, _download, _selectPipe, _selectFw, _nlpSuggest };
})();
